# Default values for metastore-spark-v2.4.7.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount -- Desired number of pods, leaderElection will be enabled
# if this is greater than 1
replicaCount: 1

image:
  # -- Image repository
  repository: gcr.io/mapr-252711/hivemeta-2.3
  # -- Image pull policy
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "202110121130-AJ"

# -- Image pull secrets
imagePullSecrets:
  - name: imagepull

# -- String to partially override `spark-operator.fullname` template (will maintain the release name)
nameOverride: ""

# -- String to override release name
fullnameOverride: ""

# -- restart policy
restartPolicy: "Always"

createDefaultPullSecret: false
defaultPullSecret: imagepull

mysqlNamespace: "mysql-operator"
mysqlSecret: "hivemetastore-mysql"
hiveSecret: "hivemeta-secret"
mysqlDB: false

automountServiceAccountToken: true

#HPE tenant namespace info
tenantIsUnsecure: false

#HPE tenant namespace service account
serviceAccount:
  # Specifies whether a service account should be created
  # This will look for existing hpe-{{ ReleaseNamespace }} ServiceAccount and use it if it exists and creates when it is not present
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  # Otherwise a new Service Account is created using hpe-{{ ReleaseNamespace }}
  name: ""

#RBAC for the ServiceAccount
rbac:
  #RBAC is created only when this flag is true and ServiceAccount.create is also true
  create: false

podSecurityContext: {}

#service info
service:
  type: ClusterIP
  port: 9083
  name: "hivemeta-svc"

externalService:
  type: NodePort
  name: "hivemeta-ext-svc"

#container ports
ports:
  sshPort: 22
  sshHostPort: 7778
  queryPort: 9083

# resources -- Pod resource requests and limits
resources:
  limits:
    cpu: 8000m
    memory: 8Gi
    ephemeral-storage: 46Gi
  requests:
    cpu: 2000m
    memory: 8Gi
    ephemeral-storage: 46Gi

#owner Reference
ownerReference:
  overRide: false
  ownerReferences: {}
